services:
  gdal:
    build: gdal/.
  minio:
    build:
      context: minio/.
    environment:
      - DO_SPACES_ACCESS_KEY=value
      - DO_SPACES_SECRET_KEY=value
      - DO_SPACES_ENDPOINT=value
    volumes:
      - ./data:/data
      - ./minio/scripts:/scripts
  postgis:
    build:
      context: postgis/.
  tippecanoe:
    build:
      context: tippecanoe/.
