services:
  gdal:
    build: gdal/.
  minio:
    build:
      context: minio/.
    environment:
      DO_SPACES_ACCESS_KEY: $DO_SPACES_ACCESS_KEY
      DO_SPACES_SECRET_KEY: $DO_SPACES_SECRET_KEY
      DO_SPACES_ENDPOINT: $DO_SPACES_ENDPOINT
    volumes:
      - ./data:/data
      - ./minio/scripts:/scripts
  postgis:
    build:
      context: postgis/.
  tippecanoe:
    build:
      context: tippecanoe/.
